name: .NET Core Test

on:
  push:
    branches: [main]

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.100

      - name: Install dependencies - Serilog.Sinks.SentrySDK
        run: dotnet restore src/Serilog.Sinks.SentrySDK/Serilog.Sinks.SentrySDK.csproj

      - name: Install dependencies - Serilog.Sinks.SentrySDK.AspNetCore
        run: dotnet restore src/Serilog.Sinks.SentrySDK.AspNetCore/Serilog.Sinks.SentrySDK.AspNetCore.csproj

  build:
    needs: restore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.100

      - name: Build - Serilog.Sinks.SentrySDK
        run: |
          dotnet restore src/Serilog.Sinks.SentrySDK/Serilog.Sinks.SentrySDK.csproj
          dotnet build src/Serilog.Sinks.SentrySDK/Serilog.Sinks.SentrySDK.csproj --configuration Release

      - name: Build - Serilog.Sinks.SentrySDK.AspNetCore
        run: |
          dotnet restore src/Serilog.Sinks.SentrySDK.AspNetCore/Serilog.Sinks.SentrySDK.AspNetCore.csproj
          dotnet build src/Serilog.Sinks.SentrySDK.AspNetCore/Serilog.Sinks.SentrySDK.AspNetCore.csproj --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.100

      - name: Test - Serilog.Sinks.SentrySDK.AspNetCore.Tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./reports/ src/Serilog.Sinks.SentrySDK.AspNetCore.Tests/Serilog.Sinks.SentrySDK.AspNetCore.Tests.csproj

      - name: Test - Serilog.Sinks.SentrySDK.Tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./reports/ src/Serilog.Sinks.SentrySDK.Tests/Serilog.Sinks.SentrySDK.Tests.csproj

      - name: Upload coverage SentrySDK.AspNetCore.Tests to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SentrySDK.AspNetCore.Tests
          path: src/Serilog.Sinks.SentrySDK.AspNetCore.Tests/reports

      - name: Upload coverage SentrySDK.Tests to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SentrySDK.Tests
          path: src/Serilog.Sinks.SentrySDK.Tests/reports

  coverage:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Download reports SentrySDK.AspNetCore.Tests
          uses: actions/download-artifact@v3
          with:
            name: SentrySDK.AspNetCore.Tests
            path: ./reports/

        - name: Download reports SentrySDK.Tests
          uses: actions/download-artifact@v3
          with:
              name: SentrySDK.Tests
              path: ./reports/

        - name: Codecov
          uses: codecov/codecov-action@v2
          with:
            files: "./reports/coverage.cobertura.xml"
            fail_ci_if_error: true
