name: .NET Core Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100

    - name: Install dependencies
      run: dotnet restore /src/Serilog.Sinks.SentrySDK/Serilog.Sinks.SentrySDK.csproj

    - name: Install dependencies
      run: dotnet restore ./src/Serilog.Sinks.SentrySDK.AspNetCore/Serilog.Sinks.SentrySDK.AspNetCore.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test - Serilog.Sinks.SentrySDK.AspNetCore.Tests
      run: dotnet test --no-restore --verbosity normal --project ./src/Serilog.Sinks.SentrySDK.AspNetCore.Tests/Serilog.Sinks.SentrySDK.AspNetCore.Tests.csproj

    - name: Test - Serilog.Sinks.SentrySDK.Tests
      run: dotnet test --no-restore --verbosity normal --project ./src/Serilog.Sinks.SentrySDK.Tests/Serilog.Sinks.SentrySDK.Tests.csproj
